- name: Package installation
  ansible.builtin.package:
    state: present
    name: "{{package1}}"

- name: Package installation
  ansible.builtin.package:
    state: present
    name: "{{package2}}"

- name: System Update
  shell: apt update

- name: Download Package
  ansible.builtin.get_url:
    url: "{{tomcat_url}}"
    dest: /opt

- name: unzip package
  ansible.builtin.unarchive:
    src: "{{tomcatfile_src}}"
    dest: "{{tomcatfile_dest}}"
    remote_src: yes

- name: Download Artifact
  ansible.builtin.get_url:
    url: "{{tomcatstudent.war}}"
    dest: "{{tomcatstudent.war_dest}}"

- name: restart service
  shell: sh /home/ubuntu/apache-tomcat-9.0.70/bin/startup.sh