- name: ignoring errors
  hosts: all
  tasks:
  - name: ignoreerror
    shell: ps_aux | grep java | grep -v java
    ignore_errors: yes
  - name: run the process
    debug:
      msg: ignoring the process