- name: Packaging installation using playbook
  hosts: all
  become: yes
  tasks: 
  - name: Install the latest version of Apache and MariaDB
    ansible.builtin.package:
      name:
        - apache2
        - tree
      state: latest