- name: Packaging installation using playbook
  hosts: all
  become: yes
  tasks: 
  - name: httpdinstalltion
    ansible.builtin.package:
    state: present
  - name: servicerestart
    shell: systemctl restart httpd