- name: Packaging installation using playbook
  hosts: all
  become: yes
  tasks: 
    - name: httpdinstalltion
      ansible.builtin.package:
        name: httpd
        state: present
    - name: servicerestart
      shell: systemctl restart httpd