- name: temp hosting playbook
  hosts: all
  become: yes
  tasks:
  - name: package installation
    ansible.builtin.package:
      name: 
      - nginx
      - unzip
      state: present
    
  - name: download template
    ansible.builtin.get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page281/ogistic.zip
      dest: /home/ubuntu/
      remote_src: true
    
  - name: unzip
    ansible.builtin.unarchive:
      src: /home/ubuntu/ogistic.zip
      dest: /usr/share/nginx/html/
      remote_src: true

  - name: restart
    shell: service nginx restart
      #remote_src: true   
      