- name: temp hosting playbook
  hosts: all
  become: yes
  tasks:
  - name: package installation
    ansible.builtin.package:
      name: 
      - apache2
      - unzip
      state: present
    
  - name: download template
    ansible.builtin.get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page283/ninom.zip
      dest: /home/ubuntu/
      remote_src: true
    
  - name: unzip
    ansible.builtin.unarchive:
      src: /home/ubuntu/ninom.zip
      dest: /var/www/html/
      remote_src: true

  - name: restart
    shell: sudo systemctl restart apache2 