- name: temp hosting playbook
  hosts: all
  become: yes
  tasks:
  - name: package installation
    ansible.builtin.package:
      name: apache2
      state: present
    
  - name: download template
    ansible.builtin.get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page286/creative-studio.zip
      dest: /home/ubuntu/
    
  - name: unzip
    ansible.builtin.unarchive:
      src: /home/ubuntu/creative-studio.zip
      dest: /var/www/html/

  - name: restart
    shell: systemctl restart apache2    
      