- name : Variable Playbook
  hosts: all
  become: yes
  vars:
    URL: www.globalvars.com
  tasks:
    - name: variableplaybook 
      debug:
        msg: Priority of vars is for"{{URL}}"
      vars: 
        URL: www.localvars.com 
      vars_files:
        - file-vars.yml
      tasks: 
        - name: filevariable
          debug: 
            msg: Priority of vars is for "{{url}}"