- name : Variable Playbook
  hosts: all
  become: yes
  vars:
    URL: www.globalvars.com
  tasks:
    - name: variableplaybook
    vars: 
        URL: www.localvars.com 
        debug:
          msg: Priority of vars is for"{{URL}}"